// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Why Us"
          quote="Small businesses need a digital home that works as hard as they do—without the massive agency overhead."
          author="The WebLaunch Team"
          role="Mission Statement"
          imageSrc="http://img.b2bpic.net/free-photo/young-man-showing-thumb-up-white-background_1149-57.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
