// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import Button from '@/components/ui/Button';

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact" className="w-content-width mx-auto py-24">
        <div className="card p-12 flex flex-col items-center text-center gap-6">
          <h2 className="text-4xl font-bold text-foreground">Contact Us</h2>
          <p className="text-lg text-foreground/80 max-w-2xl">
            Ready to get your high-converting website? Reach out to us directly.
          </p>
          <div className="flex flex-col sm:flex-row gap-6 mt-4">
            <Button href="https://wa.me/994514944157" text="WhatsApp: +994 51 494 41 57" variant="primary" />
            <Button href="mailto:aydinmamedov004@gmail.com" text="Email: aydinmamedov004@gmail.com" variant="secondary" />
          </div>
        </div>
      </div>
  );
}
