// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
          tag="Fast, Professional, Affordable"
          title="Professional websites for a fraction of agency costs"
          description="Stop overpaying for agencies. Get your high-converting business website launched in days, not months. High performance, mobile-ready, and optimized for growth."
          primaryButton={{
            text: "Get Your Website Today",
            href: "/contact",
          }}
          secondaryButton={{
            text: "View Our Portfolio",
            href: "/portfolio",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/modern-smartphone-blank-screen-split-background_9975-133781.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/programming-background-collage_23-2149901782.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-internet-communication-network_23-2148779266.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/website-development-links-seo-webinar-cyberspace-concept_53876-120953.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-internet-communication-network-with-laptop_23-2148779281.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/3d-render-abstract-particle-design-with-shallow-depth-field_1048-14034.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
