// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Our Values"
          title="Building your success, efficiently"
          description="We cut out the bloat to give you a premium website that turns visitors into customers."
          metrics={[
            {
              value: "Affordable",
              title: "Fair Pricing",
              description: "No hidden agency markups. You pay for value, not office rent.",
              imageSrc: "http://img.b2bpic.net/free-photo/logistics-concept-device-screen_53876-124875.jpg",
            },
            {
              value: "Fast",
              title: "Rapid Deployment",
              description: "Get live in record time. We prioritize your time-to-market.",
              imageSrc: "http://img.b2bpic.net/free-photo/innovation-development-rocket-graphic-concept_53876-120019.jpg",
            },
            {
              value: "Pro",
              title: "Quality Assured",
              description: "Professional design standards that help you stand out from the noise.",
              imageSrc: "http://img.b2bpic.net/free-photo/architect-doing-okay-sign_1149-1825.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
