// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
        <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
          tag="Trusted By"
          title="Industry leaders choose us"
          description="We are proud to work with these forward-thinking brands."
          names={[
            "Alpha Corp",
            "Beta Solutions",
            "Gamma Ventures",
            "Delta Innovations",
            "Epsilon Systems",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
