// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Our Clients"
          title="What our customers say"
          description="We've helped dozens of small business owners find their voice online."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Restaurant Owner",
              quote: "Finally, a service that doesn't treat you like a cash cow. Affordable and beautiful.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-woman-smiling-kitchen_107420-12357.jpg",
            },
            {
              name: "Michael K.",
              role: "Realtor",
              quote: "I got my site in 3 days. My inquiry rate has already doubled.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/happy-friendly-mature-business-man-wearing-jacket-glasses-posing-indoors-looking-camera_74855-9997.jpg",
            },
            {
              name: "Elena R.",
              role: "Wellness Coach",
              quote: "Fast, friendly, and they actually understood what I needed. Highly recommend.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-senior-man-holding-smart-phone_23-2147935571.jpg",
            },
            {
              name: "David T.",
              role: "Contractor",
              quote: "Saved me over $5k vs what an agency quoted. Extremely happy with the results.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/businessman-smiling-looking-camera_23-2148112827.jpg",
            },
            {
              name: "Maria L.",
              role: "Retailer",
              quote: "A truly modern approach to web development. Easy process.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/mature-business-manager-office_1098-21368.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
